version: "3.7"

services:

  db:
    platform: linux/x86_64
    image: mysql:5.7
    command: [ "--lower_case_table_names=1",
      "--ignore-db-dir=lost+found",
      "--character-set-server=utf8,
      --collation-server=utf8_general_ci" ]
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: verpic_db
      MYSQL_USER: verpic
      MYSQL_PASSWORD: verpic
    restart: always
    volumes:
      - "./database/verpic_db/:/application"
    ports:
      - "3306:3306"
    container_name: verpic_mysql
    networks:
      - backend-network

  spring-boot:
    image: gcr.io/verpic-backend/image-built-with-jib
    ports:
      - "8080:8080"
    container_name: verpic-backend
    restart: always
    depends_on:
      - db
    environment:
      SPRINGBOOT_DB_USER: verpic
      SPRINGBOOT_DB_PASSWORD: verpic
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/verpic_db?useSSL=false
    networks:
      - backend-network
      - frontend-network

  mongodb:
    image: mongo:latest
    environment:
      MONGO_DB_USERNAME: verpic
      MONGO_DB_PASSWORD: verpic
    volumes:
      - "./database/mongodb/:/application"
    #command: mongod --smallfiles --logpath=/dev/null # --quiet
    container_name: "mongo"
    restart: always
    ports:
      - "27017:27017"
    networks:
      - backend-network2
    hostname: "mongo"

networks:
  backend-network:
  backend-network2:
  frontend-network: